# Change these first
owner: xoff1337 # Your GitHub username
repo: xoff1337 # Your Github repository name

# Add your sites here
sites:
  - name: 1nf
    url: https://xn--1-ztbv.xn--p1ai
  - name: 60x7.ru
    url: https://60x7.ru
  - name: HIGHTECH
    url: https://gk-ht.ru
  - name: mail.x-off.ru
    url: http://mail.x-off.ru

notifications:
  - type: discord

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /xoff1337
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Sites
  introTitle: "**Status Sites** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time**
  navbar:
    - title: Status
      href: https://xoff1337.github.io/xoff1337
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
